# Generated by Django 3.1.5 on 2021-02-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_tucao',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
